server:
  port: 7000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/doctors/**
        - id: pet-service
          uri: lb://PET-SERVICE
          predicates:
            - Path=/api/pets/**
        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/api/appointments/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
